name: Validate Data

on: 
  pull_request:
    branches:
      - main  # This triggers the workflow on pull requests targeting the main branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pdm
          pdm install
          
      - name: Run generate_models.py
        working-directory: src/wgcm_cvs
        run: pdm run python scripts/generate_models.py

      - name: Run validate.py
        working-directory: src/wgcm_cvs
        run: pdm run python scripts/validate.py


